# Generated by Django 3.1.4 on 2021-02-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='nom')),
                ('tel', models.CharField(max_length=30, verbose_name='numero telephone')),
                ('email', models.EmailField(max_length=254)),
                ('DateInscription', models.DateField(auto_now_add=True, verbose_name='Date inscription')),
            ],
        ),
    ]
