# Generated by Django 3.1.4 on 2021-02-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DateInscription',
            new_name='dateInscription',
        ),
    ]
